# Generated by Django 5.0.4 on 2024-05-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_generatedscript_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptrequest',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
