# Generated by Django 5.0.4 on 2024-05-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_alter_scriptrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
