# Generated by Django 5.0.4 on 2024-05-28 19:20

import scripts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_alter_scriptrequest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptrequest',
            name='description_file',
            field=models.FileField(blank=True, default='', upload_to=scripts.models.user_directory_path),
        ),
    ]
