# Generated by Django 5.0.4 on 2024-04-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Script',
        ),
    ]
